package selogger;

import java.lang.reflect.Field;

import selogger.logging.TypeIdMap;

public class EventId {

	public static final int EVENT_RESERVED = 0;
	public static final int EVENT_METHOD_ENTRY = 1;
	public static final int EVENT_FORMAL_PARAM = 2;
	public static final int EVENT_FORMAL_PARAM_BOOLEAN = EVENT_FORMAL_PARAM + TypeIdMap.TYPEID_BOOLEAN;
	public static final int EVENT_FORMAL_PARAM_BYTE = EVENT_FORMAL_PARAM + TypeIdMap.TYPEID_BYTE;
	public static final int EVENT_FORMAL_PARAM_CHAR = EVENT_FORMAL_PARAM + TypeIdMap.TYPEID_CHAR;
	public static final int EVENT_FORMAL_PARAM_DOUBLE = EVENT_FORMAL_PARAM + TypeIdMap.TYPEID_DOUBLE;
	public static final int EVENT_FORMAL_PARAM_FLOAT = EVENT_FORMAL_PARAM + TypeIdMap.TYPEID_FLOAT;
	public static final int EVENT_FORMAL_PARAM_INT = EVENT_FORMAL_PARAM + TypeIdMap.TYPEID_INT;
	public static final int EVENT_FORMAL_PARAM_LONG = EVENT_FORMAL_PARAM + TypeIdMap.TYPEID_LONG;
	public static final int EVENT_FORMAL_PARAM_SHORT = EVENT_FORMAL_PARAM + TypeIdMap.TYPEID_SHORT;
	public static final int EVENT_FORMAL_PARAM_OBJECT = EVENT_FORMAL_PARAM + TypeIdMap.TYPEID_OBJECT;
	public static final int EVENT_METHOD_NORMAL_EXIT = 12;
	public static final int EVENT_METHOD_NORMAL_EXIT_VOID = EVENT_METHOD_NORMAL_EXIT + TypeIdMap.TYPEID_VOID; // == EVENT_METHOD_NORMAL_EXIT    
	public static final int EVENT_METHOD_NORMAL_EXIT_BOOLEAN = EVENT_METHOD_NORMAL_EXIT + TypeIdMap.TYPEID_BOOLEAN;
	public static final int EVENT_METHOD_NORMAL_EXIT_BYTE = EVENT_METHOD_NORMAL_EXIT + TypeIdMap.TYPEID_BYTE;
	public static final int EVENT_METHOD_NORMAL_EXIT_CHAR = EVENT_METHOD_NORMAL_EXIT + TypeIdMap.TYPEID_CHAR;
	public static final int EVENT_METHOD_NORMAL_EXIT_DOUBLE = EVENT_METHOD_NORMAL_EXIT + TypeIdMap.TYPEID_DOUBLE;
	public static final int EVENT_METHOD_NORMAL_EXIT_FLOAT = EVENT_METHOD_NORMAL_EXIT + TypeIdMap.TYPEID_FLOAT;
	public static final int EVENT_METHOD_NORMAL_EXIT_INT = EVENT_METHOD_NORMAL_EXIT + TypeIdMap.TYPEID_INT;
	public static final int EVENT_METHOD_NORMAL_EXIT_LONG = EVENT_METHOD_NORMAL_EXIT + TypeIdMap.TYPEID_LONG;
	public static final int EVENT_METHOD_NORMAL_EXIT_SHORT = EVENT_METHOD_NORMAL_EXIT + TypeIdMap.TYPEID_SHORT;
	public static final int EVENT_METHOD_NORMAL_EXIT_OBJECT = EVENT_METHOD_NORMAL_EXIT + TypeIdMap.TYPEID_OBJECT;
	public static final int EVENT_METHOD_EXCEPTIONAL_EXIT = 22;
	public static final int EVENT_THROW = 23;

	public static final int EVENT_OBJECT_CREATION_COMPLETED = 24;
	public static final int EVENT_OBJECT_INITIALIZED = 25;

	public static final int EVENT_METHOD_CALL = 26;
	public static final int EVENT_ACTUAL_PARAM = 27;
	public static final int EVENT_ACTUAL_PARAM_BOOLEAN = EVENT_ACTUAL_PARAM + TypeIdMap.TYPEID_BOOLEAN;
	public static final int EVENT_ACTUAL_PARAM_BYTE = EVENT_ACTUAL_PARAM + TypeIdMap.TYPEID_BYTE;
	public static final int EVENT_ACTUAL_PARAM_CHAR = EVENT_ACTUAL_PARAM + TypeIdMap.TYPEID_CHAR;
	public static final int EVENT_ACTUAL_PARAM_DOUBLE = EVENT_ACTUAL_PARAM + TypeIdMap.TYPEID_DOUBLE;
	public static final int EVENT_ACTUAL_PARAM_FLOAT = EVENT_ACTUAL_PARAM + TypeIdMap.TYPEID_FLOAT;
	public static final int EVENT_ACTUAL_PARAM_INT = EVENT_ACTUAL_PARAM + TypeIdMap.TYPEID_INT;
	public static final int EVENT_ACTUAL_PARAM_LONG = EVENT_ACTUAL_PARAM + TypeIdMap.TYPEID_LONG;
	public static final int EVENT_ACTUAL_PARAM_SHORT = EVENT_ACTUAL_PARAM + TypeIdMap.TYPEID_SHORT;
	public static final int EVENT_ACTUAL_PARAM_OBJECT = EVENT_ACTUAL_PARAM + TypeIdMap.TYPEID_OBJECT;
	public static final int EVENT_RETURN_VALUE_AFTER_CALL = 37; 
	public static final int EVENT_RETURN_VALUE_AFTER_CALL_VOID = EVENT_RETURN_VALUE_AFTER_CALL + TypeIdMap.TYPEID_VOID; // == EVENT_RETURN_VALUE_AFTER_CALL 
	public static final int EVENT_RETURN_VALUE_AFTER_CALL_BOOLEAN = EVENT_RETURN_VALUE_AFTER_CALL + TypeIdMap.TYPEID_BOOLEAN;
	public static final int EVENT_RETURN_VALUE_AFTER_CALL_BYTE = EVENT_RETURN_VALUE_AFTER_CALL + TypeIdMap.TYPEID_BYTE;
	public static final int EVENT_RETURN_VALUE_AFTER_CALL_CHAR = EVENT_RETURN_VALUE_AFTER_CALL + TypeIdMap.TYPEID_CHAR;
	public static final int EVENT_RETURN_VALUE_AFTER_CALL_DOUBLE = EVENT_RETURN_VALUE_AFTER_CALL + TypeIdMap.TYPEID_DOUBLE;
	public static final int EVENT_RETURN_VALUE_AFTER_CALL_FLOAT = EVENT_RETURN_VALUE_AFTER_CALL + TypeIdMap.TYPEID_FLOAT;
	public static final int EVENT_RETURN_VALUE_AFTER_CALL_INT = EVENT_RETURN_VALUE_AFTER_CALL + TypeIdMap.TYPEID_INT;
	public static final int EVENT_RETURN_VALUE_AFTER_CALL_LONG = EVENT_RETURN_VALUE_AFTER_CALL + TypeIdMap.TYPEID_LONG;
	public static final int EVENT_RETURN_VALUE_AFTER_CALL_SHORT = EVENT_RETURN_VALUE_AFTER_CALL + TypeIdMap.TYPEID_SHORT;
	public static final int EVENT_RETURN_VALUE_AFTER_CALL_OBJECT = EVENT_RETURN_VALUE_AFTER_CALL + TypeIdMap.TYPEID_OBJECT;
	public static final int EVENT_CATCH = 47;
	
	public static final int EVENT_GET_INSTANCE_FIELD = 48;
	public static final int EVENT_GET_STATIC_FIELD = 49;
	public static final int EVENT_GET_FIELD_RESULT = 50;
	public static final int EVENT_GET_FIELD_RESULT_BOOLEAN = EVENT_GET_FIELD_RESULT + TypeIdMap.TYPEID_BOOLEAN;
	public static final int EVENT_GET_FIELD_RESULT_BYTE = EVENT_GET_FIELD_RESULT + TypeIdMap.TYPEID_BYTE;
	public static final int EVENT_GET_FIELD_RESULT_CHAR = EVENT_GET_FIELD_RESULT + TypeIdMap.TYPEID_CHAR;
	public static final int EVENT_GET_FIELD_RESULT_DOUBLE = EVENT_GET_FIELD_RESULT + TypeIdMap.TYPEID_DOUBLE;
	public static final int EVENT_GET_FIELD_RESULT_FLOAT = EVENT_GET_FIELD_RESULT + TypeIdMap.TYPEID_FLOAT;
	public static final int EVENT_GET_FIELD_RESULT_INT = EVENT_GET_FIELD_RESULT + TypeIdMap.TYPEID_INT;
	public static final int EVENT_GET_FIELD_RESULT_LONG = EVENT_GET_FIELD_RESULT + TypeIdMap.TYPEID_LONG;
	public static final int EVENT_GET_FIELD_RESULT_SHORT = EVENT_GET_FIELD_RESULT + TypeIdMap.TYPEID_SHORT;
	public static final int EVENT_GET_FIELD_RESULT_OBJECT = EVENT_GET_FIELD_RESULT + TypeIdMap.TYPEID_OBJECT;
	public static final int EVENT_PUT_INSTANCE_FIELD = 60;
	public static final int EVENT_PUT_INSTANCE_FIELD_BOOLEAN = EVENT_PUT_INSTANCE_FIELD + TypeIdMap.TYPEID_BOOLEAN;
	public static final int EVENT_PUT_INSTANCE_FIELD_BYTE = EVENT_PUT_INSTANCE_FIELD + TypeIdMap.TYPEID_BYTE;
	public static final int EVENT_PUT_INSTANCE_FIELD_CHAR = EVENT_PUT_INSTANCE_FIELD + TypeIdMap.TYPEID_CHAR;
	public static final int EVENT_PUT_INSTANCE_FIELD_DOUBLE = EVENT_PUT_INSTANCE_FIELD + TypeIdMap.TYPEID_DOUBLE;
	public static final int EVENT_PUT_INSTANCE_FIELD_FLOAT = EVENT_PUT_INSTANCE_FIELD + TypeIdMap.TYPEID_FLOAT;
	public static final int EVENT_PUT_INSTANCE_FIELD_INT = EVENT_PUT_INSTANCE_FIELD + TypeIdMap.TYPEID_INT;
	public static final int EVENT_PUT_INSTANCE_FIELD_LONG = EVENT_PUT_INSTANCE_FIELD + TypeIdMap.TYPEID_LONG;
	public static final int EVENT_PUT_INSTANCE_FIELD_SHORT = EVENT_PUT_INSTANCE_FIELD + TypeIdMap.TYPEID_SHORT;
	public static final int EVENT_PUT_INSTANCE_FIELD_OBJECT = EVENT_PUT_INSTANCE_FIELD + TypeIdMap.TYPEID_OBJECT;
	public static final int EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION = 70;
	public static final int EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION_BOOLEAN = EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION + TypeIdMap.TYPEID_BOOLEAN;
	public static final int EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION_BYTE = EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION + TypeIdMap.TYPEID_BYTE;
	public static final int EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION_CHAR = EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION + TypeIdMap.TYPEID_CHAR;
	public static final int EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION_DOUBLE = EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION + TypeIdMap.TYPEID_DOUBLE;
	public static final int EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION_FLOAT = EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION + TypeIdMap.TYPEID_FLOAT;
	public static final int EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION_INT = EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION + TypeIdMap.TYPEID_INT;
	public static final int EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION_LONG = EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION + TypeIdMap.TYPEID_LONG;
	public static final int EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION_SHORT = EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION + TypeIdMap.TYPEID_SHORT;
	public static final int EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION_OBJECT = EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION + TypeIdMap.TYPEID_OBJECT;
	public static final int EVENT_PUT_STATIC_FIELD = 80;
	public static final int EVENT_PUT_STATIC_FIELD_BOOLEAN = EVENT_PUT_STATIC_FIELD + TypeIdMap.TYPEID_BOOLEAN;
	public static final int EVENT_PUT_STATIC_FIELD_BYTE = EVENT_PUT_STATIC_FIELD + TypeIdMap.TYPEID_BYTE;
	public static final int EVENT_PUT_STATIC_FIELD_CHAR = EVENT_PUT_STATIC_FIELD + TypeIdMap.TYPEID_CHAR;
	public static final int EVENT_PUT_STATIC_FIELD_DOUBLE = EVENT_PUT_STATIC_FIELD + TypeIdMap.TYPEID_DOUBLE;
	public static final int EVENT_PUT_STATIC_FIELD_FLOAT = EVENT_PUT_STATIC_FIELD + TypeIdMap.TYPEID_FLOAT;
	public static final int EVENT_PUT_STATIC_FIELD_INT = EVENT_PUT_STATIC_FIELD + TypeIdMap.TYPEID_INT;
	public static final int EVENT_PUT_STATIC_FIELD_LONG = EVENT_PUT_STATIC_FIELD + TypeIdMap.TYPEID_LONG;
	public static final int EVENT_PUT_STATIC_FIELD_SHORT = EVENT_PUT_STATIC_FIELD + TypeIdMap.TYPEID_SHORT;
	public static final int EVENT_PUT_STATIC_FIELD_OBJECT = EVENT_PUT_STATIC_FIELD + TypeIdMap.TYPEID_OBJECT;

	public static final int EVENT_ARRAY_LOAD = 90;
	public static final int EVENT_ARRAY_LOAD_RESULT = 91;
	public static final int EVENT_ARRAY_LOAD_RESULT_BOOLEAN = EVENT_ARRAY_LOAD_RESULT + TypeIdMap.TYPEID_BOOLEAN;
	public static final int EVENT_ARRAY_LOAD_RESULT_BYTE = EVENT_ARRAY_LOAD_RESULT + TypeIdMap.TYPEID_BYTE;
	public static final int EVENT_ARRAY_LOAD_RESULT_CHAR = EVENT_ARRAY_LOAD_RESULT + TypeIdMap.TYPEID_CHAR;
	public static final int EVENT_ARRAY_LOAD_RESULT_DOUBLE = EVENT_ARRAY_LOAD_RESULT + TypeIdMap.TYPEID_DOUBLE;
	public static final int EVENT_ARRAY_LOAD_RESULT_FLOAT = EVENT_ARRAY_LOAD_RESULT + TypeIdMap.TYPEID_FLOAT;
	public static final int EVENT_ARRAY_LOAD_RESULT_INT = EVENT_ARRAY_LOAD_RESULT + TypeIdMap.TYPEID_INT;
	public static final int EVENT_ARRAY_LOAD_RESULT_LONG = EVENT_ARRAY_LOAD_RESULT + TypeIdMap.TYPEID_LONG;
	public static final int EVENT_ARRAY_LOAD_RESULT_SHORT = EVENT_ARRAY_LOAD_RESULT + TypeIdMap.TYPEID_SHORT;
	public static final int EVENT_ARRAY_LOAD_RESULT_OBJECT = EVENT_ARRAY_LOAD_RESULT + TypeIdMap.TYPEID_OBJECT;
	public static final int EVENT_ARRAY_STORE = 101;
	public static final int EVENT_ARRAY_STORE_BOOLEAN = EVENT_ARRAY_STORE + TypeIdMap.TYPEID_BOOLEAN;
	public static final int EVENT_ARRAY_STORE_BYTE = EVENT_ARRAY_STORE + TypeIdMap.TYPEID_BYTE;
	public static final int EVENT_ARRAY_STORE_CHAR = EVENT_ARRAY_STORE + TypeIdMap.TYPEID_CHAR;
	public static final int EVENT_ARRAY_STORE_DOUBLE = EVENT_ARRAY_STORE + TypeIdMap.TYPEID_DOUBLE;
	public static final int EVENT_ARRAY_STORE_FLOAT = EVENT_ARRAY_STORE + TypeIdMap.TYPEID_FLOAT;
	public static final int EVENT_ARRAY_STORE_INT = EVENT_ARRAY_STORE + TypeIdMap.TYPEID_INT;
	public static final int EVENT_ARRAY_STORE_LONG = EVENT_ARRAY_STORE + TypeIdMap.TYPEID_LONG;
	public static final int EVENT_ARRAY_STORE_SHORT = EVENT_ARRAY_STORE + TypeIdMap.TYPEID_SHORT;
	public static final int EVENT_ARRAY_STORE_OBJECT = EVENT_ARRAY_STORE + TypeIdMap.TYPEID_OBJECT;

	public static final int EVENT_NEW_ARRAY = 111;
	public static final int EVENT_MULTI_NEW_ARRAY = 112;
	public static final int EVENT_MULTI_NEW_ARRAY_CONTENT = 113;
	public static final int EVENT_ARRAY_LENGTH = 114;
	public static final int EVENT_ARRAY_LENGTH_RESULT = 115;

	public static final int EVENT_INSTANCEOF = 116;
	public static final int EVENT_MONITOR_ENTER = 117;
	public static final int EVENT_MONITOR_EXIT = 118;

	public static final int EVENT_LABEL = 119;
	public static final int EVENT_CONSTANT_OBJECT_LOAD = 120;
	
	public static final int MAX_EVENT_TYPE = 120;
	
	public static final int[] BASE_EVENT = new int[] {
		EVENT_RESERVED, 
		EVENT_METHOD_ENTRY, 
		EVENT_FORMAL_PARAM,
		EVENT_FORMAL_PARAM,
		EVENT_FORMAL_PARAM,
		EVENT_FORMAL_PARAM,
		EVENT_FORMAL_PARAM,
		EVENT_FORMAL_PARAM,
		EVENT_FORMAL_PARAM,
		EVENT_FORMAL_PARAM,
		EVENT_FORMAL_PARAM,
		EVENT_FORMAL_PARAM,
		EVENT_METHOD_NORMAL_EXIT,
		EVENT_METHOD_NORMAL_EXIT,
		EVENT_METHOD_NORMAL_EXIT,
		EVENT_METHOD_NORMAL_EXIT,
		EVENT_METHOD_NORMAL_EXIT,
		EVENT_METHOD_NORMAL_EXIT,
		EVENT_METHOD_NORMAL_EXIT,
		EVENT_METHOD_NORMAL_EXIT,
		EVENT_METHOD_NORMAL_EXIT,
		EVENT_METHOD_NORMAL_EXIT,
		EVENT_METHOD_EXCEPTIONAL_EXIT,
		EVENT_THROW,
		EVENT_OBJECT_CREATION_COMPLETED,
		EVENT_OBJECT_INITIALIZED,
		EVENT_METHOD_CALL, 
		EVENT_ACTUAL_PARAM,
		EVENT_ACTUAL_PARAM,
		EVENT_ACTUAL_PARAM,
		EVENT_ACTUAL_PARAM,
		EVENT_ACTUAL_PARAM,
		EVENT_ACTUAL_PARAM,
		EVENT_ACTUAL_PARAM,
		EVENT_ACTUAL_PARAM,
		EVENT_ACTUAL_PARAM,
		EVENT_ACTUAL_PARAM,
		EVENT_RETURN_VALUE_AFTER_CALL,
		EVENT_RETURN_VALUE_AFTER_CALL,
		EVENT_RETURN_VALUE_AFTER_CALL,
		EVENT_RETURN_VALUE_AFTER_CALL,
		EVENT_RETURN_VALUE_AFTER_CALL,
		EVENT_RETURN_VALUE_AFTER_CALL,
		EVENT_RETURN_VALUE_AFTER_CALL,
		EVENT_RETURN_VALUE_AFTER_CALL,
		EVENT_RETURN_VALUE_AFTER_CALL,
		EVENT_RETURN_VALUE_AFTER_CALL,
		EVENT_CATCH,
		EVENT_GET_INSTANCE_FIELD,
		EVENT_GET_STATIC_FIELD,
		EVENT_GET_FIELD_RESULT,
		EVENT_GET_FIELD_RESULT,
		EVENT_GET_FIELD_RESULT,
		EVENT_GET_FIELD_RESULT,
		EVENT_GET_FIELD_RESULT,
		EVENT_GET_FIELD_RESULT,
		EVENT_GET_FIELD_RESULT,
		EVENT_GET_FIELD_RESULT,
		EVENT_GET_FIELD_RESULT,
		EVENT_GET_FIELD_RESULT,
		EVENT_PUT_INSTANCE_FIELD,
		EVENT_PUT_INSTANCE_FIELD,
		EVENT_PUT_INSTANCE_FIELD,
		EVENT_PUT_INSTANCE_FIELD,
		EVENT_PUT_INSTANCE_FIELD,
		EVENT_PUT_INSTANCE_FIELD,
		EVENT_PUT_INSTANCE_FIELD,
		EVENT_PUT_INSTANCE_FIELD,
		EVENT_PUT_INSTANCE_FIELD,
		EVENT_PUT_INSTANCE_FIELD,
		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
		EVENT_PUT_STATIC_FIELD,
		EVENT_PUT_STATIC_FIELD,
		EVENT_PUT_STATIC_FIELD,
		EVENT_PUT_STATIC_FIELD,
		EVENT_PUT_STATIC_FIELD,
		EVENT_PUT_STATIC_FIELD,
		EVENT_PUT_STATIC_FIELD,
		EVENT_PUT_STATIC_FIELD,
		EVENT_PUT_STATIC_FIELD,
		EVENT_PUT_STATIC_FIELD,
		EVENT_ARRAY_LOAD,
		EVENT_ARRAY_LOAD_RESULT,
		EVENT_ARRAY_LOAD_RESULT,
		EVENT_ARRAY_LOAD_RESULT,
		EVENT_ARRAY_LOAD_RESULT,
		EVENT_ARRAY_LOAD_RESULT,
		EVENT_ARRAY_LOAD_RESULT,
		EVENT_ARRAY_LOAD_RESULT,
		EVENT_ARRAY_LOAD_RESULT,
		EVENT_ARRAY_LOAD_RESULT,
		EVENT_ARRAY_LOAD_RESULT,
		EVENT_ARRAY_STORE,
		EVENT_ARRAY_STORE,
		EVENT_ARRAY_STORE,
		EVENT_ARRAY_STORE,
		EVENT_ARRAY_STORE,
		EVENT_ARRAY_STORE,
		EVENT_ARRAY_STORE,
		EVENT_ARRAY_STORE,
		EVENT_ARRAY_STORE,
		EVENT_ARRAY_STORE,
		EVENT_NEW_ARRAY,
		EVENT_MULTI_NEW_ARRAY,
		EVENT_MULTI_NEW_ARRAY_CONTENT, 
		EVENT_ARRAY_LENGTH,
		EVENT_ARRAY_LENGTH_RESULT,
		EVENT_INSTANCEOF,
		EVENT_MONITOR_ENTER,
		EVENT_MONITOR_EXIT,
		EVENT_LABEL,
		EVENT_CONSTANT_OBJECT_LOAD
	};
	
	public static final String[] EVENT_NAMES = new String[] {
		"RESERVED",
		"METHOD_ENTRY",
		"FORMAL_PARAM",
		"FORMAL_PARAM:BOOLEAN",
		"FORMAL_PARAM:BYTE",
		"FORMAL_PARAM:CHAR",
		"FORMAL_PARAM:DOUBLE",
		"FORMAL_PARAM:FLOAT",
		"FORMAL_PARAM:INT",
		"FORMAL_PARAM:LONG",
		"FORMAL_PARAM:SHORT",
		"FORMAL_PARAM:OBJECT",
		"METHOD_NORMAL_EXIT",
		"METHOD_NORMAL_EXIT:BOOLEAN",
		"METHOD_NORMAL_EXIT:BYTE",
		"METHOD_NORMAL_EXIT:CHAR",
		"METHOD_NORMAL_EXIT:DOUBLE",
		"METHOD_NORMAL_EXIT:FLOAT",
		"METHOD_NORMAL_EXIT:INT",
		"METHOD_NORMAL_EXIT:LONG",
		"METHOD_NORMAL_EXIT:SHORT",
		"METHOD_NORMAL_EXIT:OBJECT",
		"METHOD_EXCEPTIONAL_EXIT",
		"THROW",
		"OBJECT_CREATION_COMPLETED",
		"OBJECT_INITIALIZED",
		"METHOD_CALL",
		"ACTUAL_PARAM",
		"ACTUAL_PARAM:BOOLEAN",
		"ACTUAL_PARAM:BYTE",
		"ACTUAL_PARAM:CHAR",
		"ACTUAL_PARAM:DOUBLE",
		"ACTUAL_PARAM:FLOAT",
		"ACTUAL_PARAM:INT",
		"ACTUAL_PARAM:LONG",
		"ACTUAL_PARAM:SHORT",
		"ACTUAL_PARAM:OBJECT",
		"RETURN_VALUE_AFTER_CALL",
		"RETURN_VALUE_AFTER_CALL:BOOLEAN",
		"RETURN_VALUE_AFTER_CALL:BYTE",
		"RETURN_VALUE_AFTER_CALL:CHAR",
		"RETURN_VALUE_AFTER_CALL:DOUBLE",
		"RETURN_VALUE_AFTER_CALL:FLOAT",
		"RETURN_VALUE_AFTER_CALL:INT",
		"RETURN_VALUE_AFTER_CALL:LONG",
		"RETURN_VALUE_AFTER_CALL:SHORT",
		"RETURN_VALUE_AFTER_CALL:OBJECT",
		"CATCH",
		"GET_INSTANCE_FIELD",
		"GET_STATIC_FIELD",
		"GET_FIELD_RESULT",
		"GET_FIELD_RESULT:BOOLEAN",
		"GET_FIELD_RESULT:BYTE",
		"GET_FIELD_RESULT:CHAR",
		"GET_FIELD_RESULT:DOUBLE",
		"GET_FIELD_RESULT:FLOAT",
		"GET_FIELD_RESULT:INT",
		"GET_FIELD_RESULT:LONG",
		"GET_FIELD_RESULT:SHORT",
		"GET_FIELD_RESULT:OBJECT",
		"PUT_INSTANCE_FIELD",
		"PUT_INSTANCE_FIELD:BOOLEAN",
		"PUT_INSTANCE_FIELD:BYTE",
		"PUT_INSTANCE_FIELD:CHAR",
		"PUT_INSTANCE_FIELD:DOUBLE",
		"PUT_INSTANCE_FIELD:FLOAT",
		"PUT_INSTANCE_FIELD:INT",
		"PUT_INSTANCE_FIELD:LONG",
		"PUT_INSTANCE_FIELD:SHORT",
		"PUT_INSTANCE_FIELD:OBJECT",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:BOOLEAN",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:BYTE",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:CHAR",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:DOUBLE",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:FLOAT",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:INT",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:LONG",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:SHORT",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:OBJECT",
		"PUT_STATIC_FIELD",
		"PUT_STATIC_FIELD:BOOLEAN",
		"PUT_STATIC_FIELD:BYTE",
		"PUT_STATIC_FIELD:CHAR",
		"PUT_STATIC_FIELD:DOUBLE",
		"PUT_STATIC_FIELD:FLOAT",
		"PUT_STATIC_FIELD:INT",
		"PUT_STATIC_FIELD:LONG",
		"PUT_STATIC_FIELD:SHORT",
		"PUT_STATIC_FIELD:OBJECT",
		"ARRAY_LOAD",
		"ARRAY_LOAD_RESULT",
		"ARRAY_LOAD_RESULT:BOOLEAN",
		"ARRAY_LOAD_RESULT:BYTE",
		"ARRAY_LOAD_RESULT:CHAR",
		"ARRAY_LOAD_RESULT:DOUBLE",
		"ARRAY_LOAD_RESULT:FLOAT",
		"ARRAY_LOAD_RESULT:INT",
		"ARRAY_LOAD_RESULT:LONG",
		"ARRAY_LOAD_RESULT:SHORT",
		"ARRAY_LOAD_RESULT:OBJECT",
		"ARRAY_STORE",
		"ARRAY_STORE:BOOLEAN",
		"ARRAY_STORE:BYTE",
		"ARRAY_STORE:CHAR",
		"ARRAY_STORE:DOUBLE",
		"ARRAY_STORE:FLOAT",
		"ARRAY_STORE:INT",
		"ARRAY_STORE:LONG",
		"ARRAY_STORE:SHORT",
		"ARRAY_STORE:OBJECT",
		"NEW_ARRAY",
		"MULTI_NEW_ARRAY",
		"MULTI_NEW_ARRAY_CONTENT",
		"ARRAY_LENGTH",
		"ARRAY_LENGTH_RESULT",
		"INSTANCEOF",
		"MONITOR_ENTER",
		"MONITOR_EXIT",
		"LABEL",
		"CONSTANT_OBJECT_LOAD"
	};
	
	static {
		for (int i=0; i<BASE_EVENT.length; ++i) {
			if (hasType(i)) {
				assert (i - BASE_EVENT[i] >= 0) && (i - BASE_EVENT[i] < 10); 
			} else {
				assert BASE_EVENT[i] == i: "BASE_EVENT is not consistent for " + i;
			}
		}
		
		for (int i=0; i<EVENT_NAMES.length; ++i) {
			String name = EVENT_NAMES[i];
			try {
				Field f = EventId.class.getField("EVENT_" + name.replace(':', '_'));
				assert i == f.getInt(null): "Invalid value is assigned EVENT_NAMES[" + i + "] = " + name;
			} catch (IllegalAccessException e) {
				assert false: "Cannot access static field " + name;
			} catch (NoSuchFieldException e) {
				assert false: "Invalid string is assigned in EVENT_NAMES[" + i + "] = " + name;
			} catch (SecurityException e) {
				// ignore the exception
			}
		}
		assert EVENT_NAMES[EVENT_CATCH].equals("CATCH");
		assert EVENT_NAMES[EVENT_CONSTANT_OBJECT_LOAD].equals("CONSTANT_OBJECT_LOAD");
	}
	
	public static int getBaseEventType(int rawEventType) {
		return BASE_EVENT[rawEventType];
	}
	
	public static boolean hasType(int rawEventType) {
		switch (BASE_EVENT[rawEventType]) {
		case EVENT_FORMAL_PARAM:
		case EVENT_METHOD_NORMAL_EXIT:
		case EVENT_METHOD_EXCEPTIONAL_EXIT:
		case EVENT_THROW:
		case EVENT_CATCH:
		case EVENT_ACTUAL_PARAM:
		case EVENT_RETURN_VALUE_AFTER_CALL:
		case EVENT_GET_FIELD_RESULT:
		case EVENT_PUT_INSTANCE_FIELD:
		case EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:
		case EVENT_PUT_STATIC_FIELD:
		case EVENT_ARRAY_LOAD_RESULT:
		case EVENT_ARRAY_STORE:
		case EVENT_ARRAY_LENGTH_RESULT:
		case EVENT_INSTANCEOF:
		case EVENT_CONSTANT_OBJECT_LOAD:
			return true;
		default:
			return false;
		}
	}
	
	public static int decodeDataType(int rawEventType) {
		switch (rawEventType) {
		case EVENT_ARRAY_LENGTH_RESULT:
			return TypeIdMap.TYPEID_INT;
			
		case EVENT_INSTANCEOF:
			return TypeIdMap.TYPEID_BOOLEAN;
			
		case EVENT_CATCH:
		case EVENT_THROW:
		case EVENT_METHOD_EXCEPTIONAL_EXIT:
		case EVENT_CONSTANT_OBJECT_LOAD:
			return TypeIdMap.TYPEID_OBJECT;
		
		default:
			return rawEventType - BASE_EVENT[rawEventType];
		}
	}
	
}
