package selogger;



public enum EventType {

	RESERVED, METHOD_ENTRY, FORMAL_PARAM, 
	METHOD_NORMAL_EXIT, METHOD_EXCEPTIONAL_EXIT, METHOD_EXCEPTIONAL_EXIT_RETHROW,
	CATCH, THROW, 
	OBJECT_CREATION_COMPLETED, OBJECT_INITIALIZED, 
	CALL, ACTUAL_PARAM, CALL_RETURN, 
	GET_INSTANCE_FIELD, GET_INSTANCE_FIELD_RESULT,
	GET_STATIC_FIELD, 
	PUT_INSTANCE_FIELD, PUT_INSTANCE_FIELD_VALUE,
	PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
	PUT_STATIC_FIELD, ARRAY_LOAD, ARRAY_LOAD_INDEX, ARRAY_LOAD_RESULT, ARRAY_LOAD_FAIL,
	ARRAY_STORE, ARRAY_STORE_INDEX, ARRAY_STORE_VALUE,
	MULTI_NEW_ARRAY, MULTI_NEW_ARRAY_CONTENT,
	ARRAY_LENGTH, ARRAY_LENGTH_RESULT, 
	MONITOR_ENTER, MONITOR_EXIT, 
	CONSTANT_OBJECT_LOAD, 
	NEW_OBJECT, NEW_OBJECT_CREATION_COMPLETED,
	NEW_OBJECT_INITIALIZED, 
	NEW_ARRAY,
	NEW_ARRAY_RESULT, INSTANCEOF, INSTANCEOF_RESULT,
	LABEL, JUMP,
	LOCAL_LOAD, LOCAL_STORE, RET;
	
	
//	public static final int[] BASE_EVENT = new int[] {
//		EVENT_RESERVED, 
//		EVENT_METHOD_ENTRY, 
//		EVENT_FORMAL_PARAM,
//		EVENT_FORMAL_PARAM,
//		EVENT_FORMAL_PARAM,
//		EVENT_FORMAL_PARAM,
//		EVENT_FORMAL_PARAM,
//		EVENT_FORMAL_PARAM,
//		EVENT_FORMAL_PARAM,
//		EVENT_FORMAL_PARAM,
//		EVENT_FORMAL_PARAM,
//		EVENT_FORMAL_PARAM,
//		EVENT_METHOD_NORMAL_EXIT,
//		EVENT_METHOD_NORMAL_EXIT,
//		EVENT_METHOD_NORMAL_EXIT,
//		EVENT_METHOD_NORMAL_EXIT,
//		EVENT_METHOD_NORMAL_EXIT,
//		EVENT_METHOD_NORMAL_EXIT,
//		EVENT_METHOD_NORMAL_EXIT,
//		EVENT_METHOD_NORMAL_EXIT,
//		EVENT_METHOD_NORMAL_EXIT,
//		EVENT_METHOD_NORMAL_EXIT,
//		EVENT_METHOD_EXCEPTIONAL_EXIT,
//		EVENT_THROW,
//		EVENT_OBJECT_CREATION_COMPLETED,
//		EVENT_OBJECT_INITIALIZED,
//		EVENT_METHOD_CALL, 
//		EVENT_ACTUAL_PARAM,
//		EVENT_ACTUAL_PARAM,
//		EVENT_ACTUAL_PARAM,
//		EVENT_ACTUAL_PARAM,
//		EVENT_ACTUAL_PARAM,
//		EVENT_ACTUAL_PARAM,
//		EVENT_ACTUAL_PARAM,
//		EVENT_ACTUAL_PARAM,
//		EVENT_ACTUAL_PARAM,
//		EVENT_ACTUAL_PARAM,
//		EVENT_RETURN_VALUE_AFTER_CALL,
//		EVENT_RETURN_VALUE_AFTER_CALL,
//		EVENT_RETURN_VALUE_AFTER_CALL,
//		EVENT_RETURN_VALUE_AFTER_CALL,
//		EVENT_RETURN_VALUE_AFTER_CALL,
//		EVENT_RETURN_VALUE_AFTER_CALL,
//		EVENT_RETURN_VALUE_AFTER_CALL,
//		EVENT_RETURN_VALUE_AFTER_CALL,
//		EVENT_RETURN_VALUE_AFTER_CALL,
//		EVENT_RETURN_VALUE_AFTER_CALL,
//		EVENT_CATCH,
//		EVENT_GET_INSTANCE_FIELD,
//		EVENT_GET_INSTANCE_FIELD,
//		EVENT_GET_INSTANCE_FIELD,
//		EVENT_GET_INSTANCE_FIELD,
//		EVENT_GET_INSTANCE_FIELD,
//		EVENT_GET_INSTANCE_FIELD,
//		EVENT_GET_INSTANCE_FIELD,
//		EVENT_GET_INSTANCE_FIELD,
//		EVENT_GET_INSTANCE_FIELD,
//		EVENT_GET_INSTANCE_FIELD,
//		EVENT_GET_STATIC_FIELD,
//		EVENT_GET_STATIC_FIELD,
//		EVENT_GET_STATIC_FIELD,
//		EVENT_GET_STATIC_FIELD,
//		EVENT_GET_STATIC_FIELD,
//		EVENT_GET_STATIC_FIELD,
//		EVENT_GET_STATIC_FIELD,
//		EVENT_GET_STATIC_FIELD,
//		EVENT_GET_STATIC_FIELD,
//		EVENT_GET_STATIC_FIELD,
//		EVENT_PUT_INSTANCE_FIELD,
//		EVENT_PUT_INSTANCE_FIELD,
//		EVENT_PUT_INSTANCE_FIELD,
//		EVENT_PUT_INSTANCE_FIELD,
//		EVENT_PUT_INSTANCE_FIELD,
//		EVENT_PUT_INSTANCE_FIELD,
//		EVENT_PUT_INSTANCE_FIELD,
//		EVENT_PUT_INSTANCE_FIELD,
//		EVENT_PUT_INSTANCE_FIELD,
//		EVENT_PUT_INSTANCE_FIELD,
//		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
//		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
//		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
//		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
//		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
//		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
//		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
//		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
//		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
//		EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION,
//		EVENT_PUT_STATIC_FIELD,
//		EVENT_PUT_STATIC_FIELD,
//		EVENT_PUT_STATIC_FIELD,
//		EVENT_PUT_STATIC_FIELD,
//		EVENT_PUT_STATIC_FIELD,
//		EVENT_PUT_STATIC_FIELD,
//		EVENT_PUT_STATIC_FIELD,
//		EVENT_PUT_STATIC_FIELD,
//		EVENT_PUT_STATIC_FIELD,
//		EVENT_PUT_STATIC_FIELD,
//		EVENT_ARRAY_LOAD,
//		EVENT_ARRAY_LOAD,
//		EVENT_ARRAY_LOAD,
//		EVENT_ARRAY_LOAD,
//		EVENT_ARRAY_LOAD,
//		EVENT_ARRAY_LOAD,
//		EVENT_ARRAY_LOAD,
//		EVENT_ARRAY_LOAD,
//		EVENT_ARRAY_LOAD,
//		EVENT_ARRAY_LOAD,
//		EVENT_ARRAY_STORE,
//		EVENT_ARRAY_STORE,
//		EVENT_ARRAY_STORE,
//		EVENT_ARRAY_STORE,
//		EVENT_ARRAY_STORE,
//		EVENT_ARRAY_STORE,
//		EVENT_ARRAY_STORE,
//		EVENT_ARRAY_STORE,
//		EVENT_ARRAY_STORE,
//		EVENT_ARRAY_STORE,
//		EVENT_NEW_ARRAY,
//		EVENT_MULTI_NEW_ARRAY,
//		EVENT_MULTI_NEW_ARRAY_CONTENT, 
//		EVENT_ARRAY_LENGTH,
//		EVENT_INSTANCEOF,
//		EVENT_MONITOR_ENTER,
//		EVENT_MONITOR_EXIT,
//		EVENT_LABEL,
//		EVENT_CONSTANT_OBJECT_LOAD,
//	};
	
	public static final String[] EVENT_NAMES = new String[] {
		"RESERVED",
		"METHOD_ENTRY",
		"FORMAL_PARAM",
		"FORMAL_PARAM:BOOLEAN",
		"FORMAL_PARAM:BYTE",
		"FORMAL_PARAM:CHAR",
		"FORMAL_PARAM:DOUBLE",
		"FORMAL_PARAM:FLOAT",
		"FORMAL_PARAM:INT",
		"FORMAL_PARAM:LONG",
		"FORMAL_PARAM:SHORT",
		"FORMAL_PARAM:OBJECT",
		"METHOD_NORMAL_EXIT",
		"METHOD_NORMAL_EXIT:BOOLEAN",
		"METHOD_NORMAL_EXIT:BYTE",
		"METHOD_NORMAL_EXIT:CHAR",
		"METHOD_NORMAL_EXIT:DOUBLE",
		"METHOD_NORMAL_EXIT:FLOAT",
		"METHOD_NORMAL_EXIT:INT",
		"METHOD_NORMAL_EXIT:LONG",
		"METHOD_NORMAL_EXIT:SHORT",
		"METHOD_NORMAL_EXIT:OBJECT",
		"METHOD_EXCEPTIONAL_EXIT",
		"THROW",
		"OBJECT_CREATION_COMPLETED",
		"OBJECT_INITIALIZED",
		"METHOD_CALL",
		"ACTUAL_PARAM",
		"ACTUAL_PARAM:BOOLEAN",
		"ACTUAL_PARAM:BYTE",
		"ACTUAL_PARAM:CHAR",
		"ACTUAL_PARAM:DOUBLE",
		"ACTUAL_PARAM:FLOAT",
		"ACTUAL_PARAM:INT",
		"ACTUAL_PARAM:LONG",
		"ACTUAL_PARAM:SHORT",
		"ACTUAL_PARAM:OBJECT",
		"RETURN_VALUE_AFTER_CALL",
		"RETURN_VALUE_AFTER_CALL:BOOLEAN",
		"RETURN_VALUE_AFTER_CALL:BYTE",
		"RETURN_VALUE_AFTER_CALL:CHAR",
		"RETURN_VALUE_AFTER_CALL:DOUBLE",
		"RETURN_VALUE_AFTER_CALL:FLOAT",
		"RETURN_VALUE_AFTER_CALL:INT",
		"RETURN_VALUE_AFTER_CALL:LONG",
		"RETURN_VALUE_AFTER_CALL:SHORT",
		"RETURN_VALUE_AFTER_CALL:OBJECT",
		"CATCH",
		"GET_INSTANCE_FIELD",
		"GET_INSTANCE_FIELD:BOOLEAN",
		"GET_INSTANCE_FIELD:BYTE",
		"GET_INSTANCE_FIELD:CHAR",
		"GET_INSTANCE_FIELD:DOUBLE",
		"GET_INSTANCE_FIELD:FLOAT",
		"GET_INSTANCE_FIELD:INT",
		"GET_INSTANCE_FIELD:LONG",
		"GET_INSTANCE_FIELD:SHORT",
		"GET_INSTANCE_FIELD:OBJECT",
		"GET_STATIC_FIELD",
		"GET_STATIC_FIELD:BOOLEAN",
		"GET_STATIC_FIELD:BYTE",
		"GET_STATIC_FIELD:CHAR",
		"GET_STATIC_FIELD:DOUBLE",
		"GET_STATIC_FIELD:FLOAT",
		"GET_STATIC_FIELD:INT",
		"GET_STATIC_FIELD:LONG",
		"GET_STATIC_FIELD:SHORT",
		"GET_STATIC_FIELD:OBJECT",
		"PUT_INSTANCE_FIELD",
		"PUT_INSTANCE_FIELD:BOOLEAN",
		"PUT_INSTANCE_FIELD:BYTE",
		"PUT_INSTANCE_FIELD:CHAR",
		"PUT_INSTANCE_FIELD:DOUBLE",
		"PUT_INSTANCE_FIELD:FLOAT",
		"PUT_INSTANCE_FIELD:INT",
		"PUT_INSTANCE_FIELD:LONG",
		"PUT_INSTANCE_FIELD:SHORT",
		"PUT_INSTANCE_FIELD:OBJECT",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:BOOLEAN",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:BYTE",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:CHAR",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:DOUBLE",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:FLOAT",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:INT",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:LONG",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:SHORT",
		"PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:OBJECT",
		"PUT_STATIC_FIELD",
		"PUT_STATIC_FIELD:BOOLEAN",
		"PUT_STATIC_FIELD:BYTE",
		"PUT_STATIC_FIELD:CHAR",
		"PUT_STATIC_FIELD:DOUBLE",
		"PUT_STATIC_FIELD:FLOAT",
		"PUT_STATIC_FIELD:INT",
		"PUT_STATIC_FIELD:LONG",
		"PUT_STATIC_FIELD:SHORT",
		"PUT_STATIC_FIELD:OBJECT",
		"ARRAY_LOAD",
		"ARRAY_LOAD:BOOLEAN",
		"ARRAY_LOAD:BYTE",
		"ARRAY_LOAD:CHAR",
		"ARRAY_LOAD:DOUBLE",
		"ARRAY_LOAD:FLOAT",
		"ARRAY_LOAD:INT",
		"ARRAY_LOAD:LONG",
		"ARRAY_LOAD:SHORT",
		"ARRAY_LOAD:OBJECT",
		"ARRAY_STORE",
		"ARRAY_STORE:BOOLEAN",
		"ARRAY_STORE:BYTE",
		"ARRAY_STORE:CHAR",
		"ARRAY_STORE:DOUBLE",
		"ARRAY_STORE:FLOAT",
		"ARRAY_STORE:INT",
		"ARRAY_STORE:LONG",
		"ARRAY_STORE:SHORT",
		"ARRAY_STORE:OBJECT",
		"NEW_ARRAY",
		"MULTI_NEW_ARRAY",
		"MULTI_NEW_ARRAY_CONTENT",
		"ARRAY_LENGTH",
		"INSTANCEOF",
		"MONITOR_ENTER",
		"MONITOR_EXIT",
		"LABEL",
		"CONSTANT_OBJECT_LOAD",
	};
	
//	static {
//		for (int i=0; i<BASE_EVENT.length; ++i) {
//			if (hasType(i)) {
//				assert (i - BASE_EVENT[i] >= 0) && (i - BASE_EVENT[i] < 10); 
//			} else {
//				assert BASE_EVENT[i] == i: "BASE_EVENT is not consistent for " + i;
//			}
//		}
//		
//		for (int i=0; i<EVENT_NAMES.length; ++i) {
//			String name = EVENT_NAMES[i];
//			try {
//				Field f = EventId.class.getField("EVENT_" + name.replace(':', '_'));
//				assert i == f.getInt(null): "Invalid value is assigned EVENT_NAMES[" + i + "] = " + name;
//			} catch (IllegalAccessException e) {
//				assert false: "Cannot access static field " + name;
//			} catch (NoSuchFieldException e) {
//				assert false: "Invalid string is assigned in EVENT_NAMES[" + i + "] = " + name;
//			} catch (SecurityException e) {
//				// ignore the exception
//			}
//		}
//		assert EVENT_NAMES[EVENT_CATCH].equals("CATCH");
//		assert EVENT_NAMES[EVENT_CONSTANT_OBJECT_LOAD].equals("CONSTANT_OBJECT_LOAD");
//	}
	
//	public static int getBaseEventType(int rawEventType) {
//		return BASE_EVENT[rawEventType];
//	}
	
//	public static boolean hasType(int rawEventType) {
//		switch (BASE_EVENT[rawEventType]) {
//		case EVENT_FORMAL_PARAM:
//		case EVENT_METHOD_NORMAL_EXIT:
//		case EVENT_METHOD_EXCEPTIONAL_EXIT:
//		case EVENT_THROW:
//		case EVENT_CATCH:
//		case EVENT_ACTUAL_PARAM:
//		case EVENT_RETURN_VALUE_AFTER_CALL:
//		case EVENT_GET_INSTANCE_FIELD:
//		case EVENT_GET_STATIC_FIELD:
//		case EVENT_PUT_INSTANCE_FIELD:
//		case EVENT_PUT_INSTANCE_FIELD_BEFORE_INITIALIZATION:
//		case EVENT_PUT_STATIC_FIELD:
//		case EVENT_ARRAY_LENGTH:
//		case EVENT_ARRAY_LOAD:
//		case EVENT_ARRAY_STORE:
//		case EVENT_INSTANCEOF:
//		case EVENT_CONSTANT_OBJECT_LOAD:
//			return true;
//		default:
//			return false;
//		}
//	}
	
//	public static int decodeDataType(int rawEventType) {
//		switch (rawEventType) {
//		case EVENT_ARRAY_LENGTH:
//			return TypeIdMap.TYPEID_INT;
//			
//		case EVENT_INSTANCEOF:
//			return TypeIdMap.TYPEID_BOOLEAN;
//			
//		case EVENT_CATCH:
//		case EVENT_THROW:
//		case EVENT_METHOD_EXCEPTIONAL_EXIT:
//		case EVENT_CONSTANT_OBJECT_LOAD:
//		case EVENT_MULTI_NEW_ARRAY_CONTENT:
//			return TypeIdMap.TYPEID_OBJECT;
//		
//		default:
//			return rawEventType - BASE_EVENT[rawEventType];
//		}
//	}
	
}
